version: "3.8"

networks:
  main:
    name: main

volumes:
  galera1-data:
  galera2-data:

services:
  galera1:
    image: bitnamicharts/mariadb-galera:sha256-ecf146d197eddfb3c473caeb8c9ddc5f54debe53a449e2d2ce9753764b02a6a9
    hostname: galera1
    environment:
      MARIADB_ROOT_PASSWORD: "rootpass"
      MARIADB_DATABASE: mydb
      MARIADB_USER: app
      MARIADB_PASSWORD: "1"
      MARIADB_GALERA_CLUSTER_NAME: galera
      MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://
      MARIADB_GALERA_CLUSTER_NODE_NAME: galera1
      MARIADB_GALERA_CLUSTER_NODE_ADDRESS: galera1
      MARIADB_GALERA_MARIABACKUP_USER: mariabackup
      MARIADB_GALERA_MARIABACKUP_PASSWORD: "mariabackup"
      MARIADB_REPLICATION_USER: replication
      MARIADB_REPLICATION_PASSWORD: "replpass"
    volumes:
      - galera1-data:/bitnami/mariadb
    networks:
      - main
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb-galera/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == worker1

  galera2:
    image: bitnamicharts/mariadb-galera:sha256-ecf146d197eddfb3c473caeb8c9ddc5f54debe53a449e2d2ce9753764b02a6a9
    hostname: galera2
    environment:
      MARIADB_ROOT_PASSWORD: "rootpass"
      MARIADB_DATABASE: mydb
      MARIADB_USER: app
      MARIADB_PASSWORD: "1"
      MARIADB_GALERA_CLUSTER_NAME: galera
      MARIADB_GALERA_CLUSTER_ADDRESS: gcomm://galera1:4567
      MARIADB_GALERA_CLUSTER_NODE_NAME: galera2
      MARIADB_GALERA_CLUSTER_NODE_ADDRESS: galera2
      MARIADB_GALERA_MARIABACKUP_USER: mariabackup
      MARIADB_GALERA_MARIABACKUP_PASSWORD: "mariabackup"
      MARIADB_REPLICATION_USER: replication
      MARIADB_REPLICATION_PASSWORD: "replpass"
    volumes:
      - galera2-data:/bitnami/mariadb
    networks:
      - main
    depends_on:
      - galera1
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == worker2


  haproxy:
    image: haproxy:3.4-dev-alpine
    networks:
      - main
    ports:
      - "80:80"
      - "3306:3306"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == master

  backend:
    image: exzenzia/backend:v4_mariadb_galera
    networks:
      - main
    environment:
      DATABASE_URL: "mysql://app:1@haproxy:3306/mydb"
      NODE_ENV: production
      JWT_SECRET: supersecretkey
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == master
    depends_on:
      - haproxy
    ports:
      - "5555:5555"
      - "3000:3000"

  frontend:
    image: exzenzia/frontend:v5
    networks:
      - main
    environment:
      - PORT=3001
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == master
