apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  NODE_ENV: "production"
  CLIENT_URL: "http://10.10.10.10:30080"
  NEXT_PUBLIC_API_BASE_URL: "http://10.10.10.10:30080/api"
  NEST_WEB_URL: "http://10.10.10.10:30080"
  COOKIE_DOMAIN: "10.10.10.10"
