apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce
type: Opaque
stringData:
  JWT_SECRET: "supersecretkey"
  DATABASE_URL: "postgresql://appuser:vnA8xhk5vogSe4EqBRx9CpGO6qvm2OkCiugv1AdquA2paT9uyqJiTsWmduVt83vw@postgres-cluster.database.svc:5432/ecommerce?schema=public"
