apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://app:m5hiyKBCyVM0OtZQmN15Q3fwxcVGrj9nppuFnR8ymuWJIwPXjxl0ctSk2bzIfc8i@pg-cluster-rw.database.svc.cluster.local:5432/app"
  JWT_SECRET: "supersecretkey"
  NODE_ENV: "production"
  NEST_WEB_URL: "https://172.21.0.3"
  CLIENT_URL: "https://172.21.0.3"
  COOKIE_DOMAIN: "172.21.0.3"
