apiVersion: v1
kind: ConfigMap
metadata:
    name: haproxy-config
    namespace: default
    labels:
        app: haproxy
data:
    haproxy.cfg: |
        global
            maxconn 100
            log stdout format raw local0

        defaults
            log global
            mode tcp
            retries 2
            timeout client 30m
            timeout connect 4s
            timeout server 30m
            timeout check 5s

        listen stats
            mode http
            bind *:7000
            stats enable
            stats uri /

        listen primary
            bind *:5000
            option httpchk GET /master
            http-check expect status 200
            default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
            server patroni-0 patroni-0.patroni.default.svc.cluster.local:5432 maxconn 100 check port 8008
            server patroni-1 patroni-1.patroni.default.svc.cluster.local:5432 maxconn 100 check port 8008

        listen replicas
            bind *:5001
            balance roundrobin
            option httpchk GET /replica
            http-check expect status 200
            default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
            server patroni-0 patroni-0.patroni.default.svc.cluster.local:5432 maxconn 100 check port 8008
            server patroni-1 patroni-1.patroni.default.svc.cluster.local:5432 maxconn 100 check port 8008

        listen all
            bind *:5432
            option httpchk GET /health
            http-check expect status 200
            default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
            server patroni-0 patroni-0.patroni.default.svc.cluster.local:5432 maxconn 100 check port 8008
            server patroni-1 patroni-1.patroni.default.svc.cluster.local:5432 maxconn 100 check port 8008
