apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
  - namespace.yaml
  - backend-secret.yaml
  - backend.yaml
  - frontend-configmap.yaml
  - frontend.yaml
  - nginx-ssl-secret.yaml
  - nginx-configmap.yaml
  - nginx.yaml
