apiVersion: v1
kind: ConfigMap
metadata:
    name: patroni-config
    namespace: default
    labels:
        app: patroni
        cluster: postgres-cluster
data:
    SPILO_CONFIGURATION: |
        bootstrap:
          dcs:
            ttl: 30
            loop_wait: 10
            retry_timeout: 10
            maximum_lag_on_failover: 1048576
            postgresql:
              use_pg_rewind: true
              use_slots: true
              parameters:
                max_connections: 100
                shared_buffers: 128MB
                effective_cache_size: 512MB
                maintenance_work_mem: 64MB
                checkpoint_completion_target: 0.9
                wal_buffers: 4MB
                default_statistics_target: 100
                random_page_cost: 1.1
                effective_io_concurrency: 200
                work_mem: 1310kB
                min_wal_size: 1GB
                max_wal_size: 3GB
                max_worker_processes: 2
                max_parallel_workers_per_gather: 1
                max_parallel_workers: 2
                max_parallel_maintenance_workers: 1
                hot_standby: "on"
                wal_level: replica
                wal_log_hints: "on"
                max_wal_senders: 10
                max_replication_slots: 10
          initdb:
            - encoding: UTF8
            - data-checksums
          pg_hba:
            - host replication replicator 0.0.0.0/0 md5
            - host all all 0.0.0.0/0 md5
        postgresql:
          parameters:
            unix_socket_directories: '/var/run/postgresql'
          create_replica_methods:
            - basebackup
          basebackup:
            checkpoint: 'fast'
        tags:
          nofailover: false
          noloadbalance: false
          clonefrom: false
          nosync: false
